version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: mongosh --eval "try {rs.status()} catch (err) {rs.initiate()}"
      interval: 5s
      timeout: 30s
      retries: 30

volumes:
  dbdata6: